on: [push]

jobs:
  json-test_job:
    runs-on: ubuntu-latest
    name: Test JSON schema
    steps:
    - name: JSON schema test
      id: json-test
      uses: ./actions/json-test
      with:
        test-type: 'normal'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The result was ${{ steps.json-test.outputs.result }}"
